//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fildo.Core.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fildo.Core.Resources.Texts", typeof(Texts).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean queue and play this.
        /// </summary>
        public static string CleanAndPlay {
            get {
                return ResourceManager.GetString("CleanAndPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that want download {0} songs?.
        /// </summary>
        public static string DownloadAllConfirm {
            get {
                return ResourceManager.GetString("DownloadAllConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download it.
        /// </summary>
        public static string DownloadIt {
            get {
                return ResourceManager.GetString("DownloadIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueue last..
        /// </summary>
        public static string EnqueueLast {
            get {
                return ResourceManager.GetString("EnqueueLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Downloading: {0} - {1}. Please report this on fildo.net contact form..
        /// </summary>
        public static string ErrorDownloading {
            get {
                return ResourceManager.GetString("ErrorDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting Netease playlist..
        /// </summary>
        public static string ErrorGettingNeteasePL {
            get {
                return ResourceManager.GetString("ErrorGettingNeteasePL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting results. Try again..
        /// </summary>
        public static string ErrorGettingResults {
            get {
                return ResourceManager.GetString("ErrorGettingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error searching.
        /// </summary>
        public static string ErrorSearching {
            get {
                return ResourceManager.GetString("ErrorSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with song: {0}.
        /// </summary>
        public static string ErrorWithSong {
            get {
                return ResourceManager.GetString("ErrorWithSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste here url of your Netease Playlist and tap Import button. Then this playlist will be imported on your playlists in Fildo.
        ///
        ///http://music.163.com/playlist/XXXXXX/YYYYYYYY/
        ///
        ///Or just enter that XXXXXXX because that is the Id of the playlist..
        /// </summary>
        public static string ImportNetease {
            get {
                return ResourceManager.GetString("ImportNetease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; conditions
        ///
        ///Fildo does not index nor host any mp3 files, it’s just a web interface to third party mp3 search engines.
        ///
        ///Fildo has no control over any web sites or resources which are provided by companies or persons other than Fildo.
        ///
        ///You acknowledge and agree that Fildo is not responsible for the availability or content of any such external sites or resources, and does not endorse any advertising, products or other materials on or available from such web sites or resources.
        ///
        ///You acknowledge  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must login on this app with your Fildo user to use this section. You could create your fildo user in Fildo.net (Using a PC)..
        /// </summary>
        public static string LoginBeforeImport {
            get {
                return ResourceManager.GetString("LoginBeforeImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with login, username or password incorrect..
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged, welcome {0}..
        /// </summary>
        public static string LoginOk {
            get {
                return ResourceManager.GetString("LoginOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version only works with songs from NetEase not from VK. This means you cannot get any song from VK.
        ///
        ///This require a Fildo user not a Netease one. (Fildo user not the email used to register)..
        /// </summary>
        public static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting lyric for this song.
        /// </summary>
        public static string LyricError {
            get {
                return ResourceManager.GetString("LyricError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyric not found.
        /// </summary>
        public static string LyricNotFound {
            get {
                return ResourceManager.GetString("LyricNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string MenuConfiguration {
            get {
                return ResourceManager.GetString("MenuConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Queue.
        /// </summary>
        public static string MenuDownloadQueue {
            get {
                return ResourceManager.GetString("MenuDownloadQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Netease Playlist.
        /// </summary>
        public static string MenuImportPLNetease {
            get {
                return ResourceManager.GetString("MenuImportPLNetease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 100 Playlists.
        /// </summary>
        public static string MenuLast100PL {
            get {
                return ResourceManager.GetString("MenuLast100PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string MenuLoginPL {
            get {
                return ResourceManager.GetString("MenuLoginPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyrics.
        /// </summary>
        public static string MenuLyrics {
            get {
                return ResourceManager.GetString("MenuLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Playlists.
        /// </summary>
        public static string MenuMyPL {
            get {
                return ResourceManager.GetString("MenuMyPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Queue.
        /// </summary>
        public static string MenuPlayerQueue {
            get {
                return ResourceManager.GetString("MenuPlayerQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string MenuShare {
            get {
                return ResourceManager.GetString("MenuShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version of fildo has been released please download and install it.
        ///Remember maybe you should uninstall this version first..
        /// </summary>
        public static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need Internet connection to use Fildo. 
        ///
        ///Close and try again when you has internet connection..
        /// </summary>
        public static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dont use proxy.
        /// </summary>
        public static string NoProxy {
            get {
                return ResourceManager.GetString("NoProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user or email already exists. Nothing was done..
        /// </summary>
        public static string RegisterDupe {
            get {
                return ResourceManager.GetString("RegisterDupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. No users were created..
        /// </summary>
        public static string RegisterError {
            get {
                return ResourceManager.GetString("RegisterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created new user. Now check your complete password in your mail!.
        /// </summary>
        public static string RegisterOK {
            get {
                return ResourceManager.GetString("RegisterOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save downloads under external SD. If you dont see downloaded songs, You should restart your phone.
        ///ONLY WORKS ON ANDROID 5.0 OR HIGHER.
        /// </summary>
        public static string SaveExternalSD {
            get {
                return ResourceManager.GetString("SaveExternalSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save downloads under folder named as artist/album/playlist..
        /// </summary>
        public static string SaveUnderFolder {
            get {
                return ResourceManager.GetString("SaveUnderFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        public static string SearchNotFound {
            get {
                return ResourceManager.GetString("SearchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Action to do.
        /// </summary>
        public static string SelectAction {
            get {
                return ResourceManager.GetString("SelectAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search, listen or download music with #Fildo via @FildoWebsite.
        /// </summary>
        public static string ShareText {
            get {
                return ResourceManager.GetString("ShareText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Download: {0} - {1}{2}. Because that file exits..
        /// </summary>
        public static string SkipExistDownload {
            get {
                return ResourceManager.GetString("SkipExistDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs &amp; Albums.
        /// </summary>
        public static string SongsAndAlbums {
            get {
                return ResourceManager.GetString("SongsAndAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your language (Maybe you have to close app and start again to apply changes):.
        /// </summary>
        public static string SpinnerCultureText {
            get {
                return ResourceManager.GetString("SpinnerCultureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a proxy (Only is for downloads, stream dont allow proxies).
        /// </summary>
        public static string SpinnerProxyText {
            get {
                return ResourceManager.GetString("SpinnerProxyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want delete it?.
        /// </summary>
        public static string SureDelete {
            get {
                return ResourceManager.GetString("SureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name to save the Playlist.
        /// </summary>
        public static string TextSavePL {
            get {
                return ResourceManager.GetString("TextSavePL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Playlist.
        /// </summary>
        public static string TitleSavePL {
            get {
                return ResourceManager.GetString("TitleSavePL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting Top Albums info. Try again..
        /// </summary>
        public static string TopAlbumError {
            get {
                return ResourceManager.GetString("TopAlbumError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Albums.
        /// </summary>
        public static string TopAlbums {
            get {
                return ResourceManager.GetString("TopAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting Top Artist info. Try again..
        /// </summary>
        public static string TopArtistError {
            get {
                return ResourceManager.GetString("TopArtistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Artists.
        /// </summary>
        public static string TopArtists {
            get {
                return ResourceManager.GetString("TopArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting Top Playlist info. Try again..
        /// </summary>
        public static string TopPlaylistError {
            get {
                return ResourceManager.GetString("TopPlaylistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Netease Playlists.
        /// </summary>
        public static string TopPlaylists {
            get {
                return ResourceManager.GetString("TopPlaylists", resourceCulture);
            }
        }
    }
}
